# 日志配置
logging:
  level:
    ROOT: INFO
    "[org.dubhe]": DEBUG
    # "[org.springframework.security]": DEBUG
    # "[org.springframework.cache]": TRACE
    # "[org.keycloak]": TRACE
    
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/keycloak?characterEncoding=UTF-8&useSSL=true
    username: kkuser
    password: kkuser

keycloak:
  # custom:
  #   adminUser:
  #     username: admin
  #     password: admin
  #     create-admin-user-enabled: true

  #   migration:
  #     import-enabled: true
  #     import-location: classpath:dubhe-realm.json

  connectionsJpa:
    default:
     showSql: true

  # mqttPublisher:
  #   provider: "dubhe-default"
  #   serverUri: 1
  #   username: 2
  #   password: 3
  #   clientId: 4
  #   automaticReconnect: false
  #   cleanSession: false
  #   connectionTimeout: 5
  #   keepAliveInterval: 6