server:
  port: 9000  

spring:
  application:
    name: springboot-keycloak-embedded
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/keycloak?characterEncoding=UTF-8&useSSL=true
    username: kkuser
    password: kkuser

keycloak:
  custom:
    server.contextPath: /auth
  mqttPublisher:
    provider: "logger"

  emailSender:
    provider: "mqtt"

  connectionsJpa:
    default:
     showSql: true    

# 日志配置
logging:
  level:
    ROOT: INFO
    "[org.dubhe]": DEBUG
    # "[org.springframework.security]": DEBUG
    # "[org.springframework.cache]": TRACE
    # "[org.keycloak]": TRACE



