server:
  port: 9000  

spring:
  application:
    name: springseed-keycloak-embedded

s8d.keycloak:
  custom:
    server.contextPath: /auth
  mqttPublisher:
    provider: "s8d-logger"

  emailSender:
    provider: "s8d-mqtt"





