spring:
  datasource:
    url: jdbc:mysql://mysql:3306/keycloak?characterEncoding=UTF-8&useSSL=true
    username: kkuser
    password: kkuser

# 日志配置
logging:
  level:
    ROOT: INFO

keycloak:
  custom:
    adminUser:
      username: admin
      password: admin
      create-admin-user-enabled: true    
